name: Build index.html

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Remote Repository
        uses: actions/checkout@v3
        with:
          ref: gtf-new-site-build

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run image
        uses: abatilo/actions-poetry@v2

      - name: install deps
        run: poetry install

      - name: make index.html
        run: |
          poetry run python make_site.py
          mkdir -p v2
          mv index.html v2/index.html

      - name: Commit Built Files
        run: |
          git config user.name "GitHub Action"
          git config user.email "github-action@example.com"
          git add v2
          git diff --quiet --exit-code || git commit -m "Commit built files" && git push

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
  deploy:
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

